# 개발 환경에서의 설정
spring:
  config:
    name: application-prod
    activate:
      on-profile: prod
    location: classpath:/application-prod.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true                                    # sout으로 보기에 편안한 sql 출력
        dialect: org.hibernate.dialect.MySQL8Dialect        # mysql 방언
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: info    # 하이버네이트가 생성하는 sql 로그로 출력
    org.hibernate.orm.jdbc.bind: info    # 쿼리 파라미터 로그 남김
    org.springframework.data.mongodb.core: off
    org.mongodb.driver: off
    root: debug

server:
  forward-headers-strategy: framework

file-path: ${FILE_PATH}
basic-profile-image-url: ${BASIC_PROFILE_IMAGE_URL}
