# 기본 설정
server:
  address: 0.0.0.0              # 모든 접속 허용
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB          # 요청 파일 하나의 사이즈
      max-request-size: 200MB     # 요청 전체의 사이즈

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true

logging:
  level:
    org.hibernate.SQL: debug    # 하이버네이트가 생성하는 sql 로그로 출력
    org.hibernate.orm.jdbc.bind: trace    # 쿼리 파라미터 로그 남김

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: local
    default: local