# 기본 설정
server:
  address: 0.0.0.0              # 모든 접속 허용
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB          # 요청 파일 하나의 사이즈
      max-request-size: 200MB     # 요청 전체의 사이즈

  mail:
    host: smtp.naver.com          # 네이버 SMTP 호스트 주소
    port: 465                     # 네이버 SMTP 포트
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true        # SMTP 서버와의 인증
      mail.smtp.ssl.enable: true  # SSL 보안연결(필수)

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access:
    header: Authorization
    exp: 7200000    # 2시간 7200000
  refresh:
    header: Refresh-Token
    exp: 1209600000    # 14일

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: test

---
spring:
  profiles:
    active: local
    default: local
